FIX - Duplication sub-comments on lecko extract
exo-addons/lecko pull request #19
Opened 2019-08-23 13:24 UTC by slickexo3

# FIX - Duplicates sub comments activity on lecko extracts

Fix duplicates lines during a Lecko extraction.
The tests corresponding to the extraction of comments have been updated.

2019-08-26 07:11 UTC, rdenarie requested changes

2019-08-26 07:11 UTC, rdenarie commented on service/src/test/java/org/exoplatform/lecko/service/TestUserActivityWithCommentAComment.java
> +    assertEquals(9, lines.length);
I think we should update the test TestSpaceActivityWithCommentAComment with the same assert.

2019-08-26 09:50 UTC, fdrouet commented
Hello @slickexo3, thank you for your first contribution to eXo Platform.

In order to accept your contribution, we need you to sign a Contributor License Agreement : http://developer.exoplatform.org/#id-community-contributions

2019-09-13 16:22 UTC, fdrouet commented
> Hello @slickexo3, thank you for your first contribution to eXo Platform.
> 
> In order to accept your contribution, we need you to sign a Contributor License Agreement : http://developer.exoplatform.org/#id-community-contributions

CLA received

2020-04-17 16:18 UTC, rdenarie approved these changes

2020-04-17 16:20 UTC, boubaker commented
@rdenarie please recreate it on https://github.com/exo-addons/lecko

2020-04-17 16:20 UTC, closed without merging